package com.bawie.duqilin20200106.database;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.bawie.duqilin20200106.model.bean.BeanDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "BEAN_DAO".
*/
public class BeanDaoDao extends AbstractDao<BeanDao, Void> {

    public static final String TABLENAME = "BEAN_DAO";

    /**
     * Properties of entity BeanDao.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Bena = new Property(0, String.class, "bena", false, "BENA");
    }


    public BeanDaoDao(DaoConfig config) {
        super(config);
    }
    
    public BeanDaoDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"BEAN_DAO\" (" + //
                "\"BENA\" TEXT);"); // 0: bena
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"BEAN_DAO\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, BeanDao entity) {
        stmt.clearBindings();
 
        String bena = entity.getBena();
        if (bena != null) {
            stmt.bindString(1, bena);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, BeanDao entity) {
        stmt.clearBindings();
 
        String bena = entity.getBena();
        if (bena != null) {
            stmt.bindString(1, bena);
        }
    }

    @Override
    public Void readKey(Cursor cursor, int offset) {
        return null;
    }    

    @Override
    public BeanDao readEntity(Cursor cursor, int offset) {
        BeanDao entity = new BeanDao( //
            cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0) // bena
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, BeanDao entity, int offset) {
        entity.setBena(cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0));
     }
    
    @Override
    protected final Void updateKeyAfterInsert(BeanDao entity, long rowId) {
        // Unsupported or missing PK type
        return null;
    }
    
    @Override
    public Void getKey(BeanDao entity) {
        return null;
    }

    @Override
    public boolean hasKey(BeanDao entity) {
        // TODO
        return false;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
