package com.bawie.duqilin20200106.database;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.bawie.duqilin20200106.model.bean.BeanDao;
import com.bawie.duqilin20200106.model.bean.ListBeanDao;

import com.bawie.duqilin20200106.database.BeanDaoDao;
import com.bawie.duqilin20200106.database.ListBeanDaoDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig beanDaoDaoConfig;
    private final DaoConfig listBeanDaoDaoConfig;

    private final BeanDaoDao beanDaoDao;
    private final ListBeanDaoDao listBeanDaoDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        beanDaoDaoConfig = daoConfigMap.get(BeanDaoDao.class).clone();
        beanDaoDaoConfig.initIdentityScope(type);

        listBeanDaoDaoConfig = daoConfigMap.get(ListBeanDaoDao.class).clone();
        listBeanDaoDaoConfig.initIdentityScope(type);

        beanDaoDao = new BeanDaoDao(beanDaoDaoConfig, this);
        listBeanDaoDao = new ListBeanDaoDao(listBeanDaoDaoConfig, this);

        registerDao(BeanDao.class, beanDaoDao);
        registerDao(ListBeanDao.class, listBeanDaoDao);
    }
    
    public void clear() {
        beanDaoDaoConfig.clearIdentityScope();
        listBeanDaoDaoConfig.clearIdentityScope();
    }

    public BeanDaoDao getBeanDaoDao() {
        return beanDaoDao;
    }

    public ListBeanDaoDao getListBeanDaoDao() {
        return listBeanDaoDao;
    }

}
