package com.bawie.duqilin20200106.database;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.bawie.duqilin20200106.model.bean.ListBeanDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "LIST_BEAN_DAO".
*/
public class ListBeanDaoDao extends AbstractDao<ListBeanDao, Void> {

    public static final String TABLENAME = "LIST_BEAN_DAO";

    /**
     * Properties of entity ListBeanDao.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property ListBean = new Property(0, String.class, "listBean", false, "LIST_BEAN");
    }


    public ListBeanDaoDao(DaoConfig config) {
        super(config);
    }
    
    public ListBeanDaoDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"LIST_BEAN_DAO\" (" + //
                "\"LIST_BEAN\" TEXT);"); // 0: listBean
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"LIST_BEAN_DAO\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, ListBeanDao entity) {
        stmt.clearBindings();
 
        String listBean = entity.getListBean();
        if (listBean != null) {
            stmt.bindString(1, listBean);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, ListBeanDao entity) {
        stmt.clearBindings();
 
        String listBean = entity.getListBean();
        if (listBean != null) {
            stmt.bindString(1, listBean);
        }
    }

    @Override
    public Void readKey(Cursor cursor, int offset) {
        return null;
    }    

    @Override
    public ListBeanDao readEntity(Cursor cursor, int offset) {
        ListBeanDao entity = new ListBeanDao( //
            cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0) // listBean
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, ListBeanDao entity, int offset) {
        entity.setListBean(cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0));
     }
    
    @Override
    protected final Void updateKeyAfterInsert(ListBeanDao entity, long rowId) {
        // Unsupported or missing PK type
        return null;
    }
    
    @Override
    public Void getKey(ListBeanDao entity) {
        return null;
    }

    @Override
    public boolean hasKey(ListBeanDao entity) {
        // TODO
        return false;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
